# Generated by Django 4.2 on 2023-05-25 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsapp', '0003_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersanswers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_question', to='testsapp.question', verbose_name='Test quesstion'),
        ),
    ]
