# Generated by Django 4.2 on 2023-06-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_useraccount_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
