# Generated by Django 4.2 on 2023-05-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_homework_lecture_remove_lecture_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsForLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials for lessons/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='video lessons/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of theme')),
                ('materials', models.ManyToManyField(related_name='materials_for_lesson', to='mainapp.materialsforlesson', verbose_name='Materials')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lesson name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_of_course', to='mainapp.course', verbose_name='Lesson of Course')),
                ('themes', models.ManyToManyField(related_name='themes_of_lesson', to='mainapp.materialsforlesson', verbose_name='Themes of Lesson')),
            ],
        ),
    ]
