# Generated by Django 4.2 on 2023-06-06 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_materialsforlesson_themes_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='First name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_lesson_course', to='mainapp.course', verbose_name='Trial lesson of Course')),
            ],
        ),
    ]
