# Generated by Django 4.2 on 2023-04-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_course_image_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Course type'),
        ),
    ]
