# Generated by Django 4.2 on 2023-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_triallesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, related_name='materials_for_lesson', to='mainapp.materialsforlesson', verbose_name='Materials'),
        ),
    ]
