# Generated by Django 4.2 on 2023-05-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Course period'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Course price'),
        ),
    ]
