# Generated by Django 4.2 on 2023-05-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_course_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course goal'),
        ),
    ]
